FROM python:3.13.1-bullseye
#FROM arm64v8/python:3.12.0

RUN mkdir /app
WORKDIR /app

COPY . .


RUN apt update && \
    apt install build-essential python3-dev python3-pip pkg-config -y
RUN which pip

COPY requirements.txt .
RUN pip3 install -U pip
RUN pip3 install setuptools
#RUN pip install --extra-index-url https://download.pytorch.org/whl/cpu
RUN pip3 install --no-deps -r requirements.txt


ENV PROJECT_ROOT=/app

# You might need to adjust this depending on your .env file location
COPY .env .env

# Expose the port the Flask app will use
EXPOSE 5000

CMD ["python", "start_app.py"]
